export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY';
export const GET_ALL_POST_COMMENTS = 'GET_ALL_POST_COMMENTS';
export const GET_CURRENT_POST = 'GET_CURRENT_POST';
